### PR TITLE
Emit signal messages from hey_joe, update django_hx_chatserver

### PR DESCRIPTION
**Pull request by bliedblad**
For #156... Needs review, but I think I have this working.

Things to review...
1) Python 3 reserves the word 'async', so renamed contrib/async to contrib/concurrency.

2) Used 'None' as transport in send_signal call, not sure if this is correct.

3) Added guid to '_WayDownSouth' and set it in ''onOpen' function. Am just matching older code here. Maybe it is not needed.

4) Updated example instructions -> use pipenv 

Question...
I was not able to figure out how to set 'allow_free_redirect' in '_WayDownSouth', or understand what it does... but found that 'self.guid' was not defined while debugging; hence line item 3.

### CODE REVIEW

**Comment by bliedblad** [comment]
@jMyles - Not sure why ci/circleci failed. I did not change Pipfile or Pipfile.lock.
Once this passes, what is the process for releasing another version? Would like to place hendrix in my project's Pipfile rather than use a modified version from git.

**Comment by jMyles** [comment]
Hey @bliedblad - thanks so much for this contribution.

I have a bunch of PRs to review and merge over at @NuCypher, but I will definitely... ahem... circle back around to this.  :-)

@KPrasch might also have some early insight as to why the Circle build is failing.

**Comment by KPrasch** [comment]
Looks like the failure is due to a Django security warning found with `pipenv check`.  I surmise the `Pipfile` and/or `Pipfile.lock` need to be updated with a different version specifier for django.


<https://circleci.com/gh/hendrix/hendrix/68?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link>
```
Checking installed package safety…

36546: requests <=2.19.1 resolved (2.19.1 installed)!
The Requests package before 2.19.1 sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.

36522: django <2.1.2,>=2.1 resolved (2.1 installed)!
An issue was discovered in Django 2.1 before 2.1.2, in which unprivileged users can read the password hashes of arbitrary accounts. The read-only password widget used by the Django Admin to display an obfuscated password hash was bypassed if a user has only the "view" permission (new in Django 2.1), resulting in display of the entire password hash to those users. This may result in a vulnerability for sites with legacy user accounts using insecure hashes.

36517: django <2.1.2,>=2.1.0 resolved (2.1 installed)!
django before 2.1.2 fixes a security bug in 2.1.x. 

```

**Comment by bliedblad** [comment]
Is that something I need to do for my PR, or is it an issue with the main repo?

**Comment by jMyles** [comment]
Hey @bliedblad - just coming back around to look at this.  It looks like among the reasons that the CI is failing is an issue in pytest-twisted: pytest-dev/pytest-twisted#45

I think we'll wait until a release up there before merging.  That cool with you?

**Comment by bliedblad** [comment]
Yeah, no problem - I have control over the hardware, so I can manually patch for now.

**Comment by KPrasch** [comment]
@bliedblad - Are you able to rebase over master?  Thank You!

**Comment by bliedblad** [comment]
Hey @KPrasch, I *think* I did the rebase correctly, but let me know.

looks like your mods for release 3.2.1 managed to capture all the changes I had in this PR except  the inclusion of jquery static file and whitespace - so probably doesn't even need to be merged?

**Comment by jMyles** [comment]
@bliedblad: Indeed, I included your commit (rebased as `7aa17ca002cbeb68617412f05f4ad8f160223720`).  Congrats - you're our 10th contributor!  :-)

And yeah, I did remove the static jquery file in favor of a CDN - no reason to track jquery in the repo.  

I think that this PR can safely be closed since your contribution is already in.

**Pull request closed without merging**
